; File uploads
upload_max_filesize = 100M
post_max_size = 100M

; Memory and execution
memory_limit = 256M
max_execution_time = 120
max_input_time = 120

; Logging
display_errors = Off
log_errors = On
error_log = /dev/stderr

; Security
expose_php = Off
disable_functions = exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source

; Date/Time
date.timezone = UTC
