; ============================
; PHP config — DEVELOPMENT
; ============================

; File uploads
upload_max_filesize = 100M
post_max_size = 100M

; Memory and execution
memory_limit = 512M
max_execution_time = 0
max_input_time = -1

; Errors — показывать всё в dev
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /dev/stderr
error_reporting = E_ALL

; Security — отключаем ограничения для dev
expose_php = On
; disable_functions — не ограничиваем в dev

; Date/Time
date.timezone = Asia/Tashkent
